[font]
normal = {family = "JetbrainsMono Nerd Font", style = "Regular"}
# normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
size = 12

[general]
import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[window]
padding = { x = 10, y = 10}
